In [3]:
import numpy as np
from datascience import *

### Use computer to decide your lunch choice

In [4]:
lunch = make_array('pizza','steak','tuna','yogurt','Chik-Fil-a')

In [5]:
eat = np.random.choice(lunch)

In [6]:
print(f'You WILL eat {eat} for lunch today!')

You WILL eat tuna for lunch today!


### Compute your lunch cost with conditional

In [7]:
if eat == 'pizza':
    cost = 4
elif eat == 'steak':
    cost = 11
elif eat == 'tuna':
    cost = 7
elif eat == 'yogurt':
    cost = 4.5
elif eat == 'Chik-Fil-a':
    cost = 15
else:
    cost = 0

In [8]:
print(f'You cost for eating {eat} for lunch today is ${cost}!')

You cost for eating tuna for lunch today is $7!


## Simulate Eagles - Cowboys 2026 Thanksgiving Game Outcome

Simple model - all scores equally probable

In [72]:
eagles = np.arange(44)
cowboys = np.arange(44)

In [73]:
eagles

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [9]:
es = np.random.choice(eagles)
cs = np.random.choice(cowboys)

In [10]:
print(f'Sample game, Eagles {es}: Cowboys {cs}')

Sample game, Eagles 36: Cowboys 36


### Improved scoring

In [11]:
realistic_scores = [0, 3, 6, 7, 10, 13, 14, 17, 20, 21,
                    23, 24, 27, 28, 30, 31, 34, 35, 38, 41, 42, 45]

#### Choose from realistic scores

In [12]:
es = np.random.choice(realistic_scores)
cs = np.random.choice(realistic_scores)

In [13]:
print(f'Sample game, Eagles {es}: Cowboys {cs}')

Sample game, Eagles 7: Cowboys 41


In [14]:
if es > cs:
    print('WIN')
elif es == cs:
    print('TIE')
else:
    print('Lose')

Lose


In [15]:
simscore = Table().with_columns('Eagles', np.random.choice(realistic_scores,5000),
                                'Cowboys', np.random.choice(realistic_scores,5000))
simscore

Eagles,Cowboys
3,28
27,35
31,14
0,34
42,38
23,7
30,38
14,41
42,17
23,34


In [16]:
simscore=simscore.with_columns('Eagles Win', simscore.column('Eagles')>simscore.column('Cowboys'))
simscore

Eagles,Cowboys,Eagles Win
3,28,False
27,35,False
31,14,True
0,34,False
42,38,True
23,7,True
30,38,False
14,41,False
42,17,True
23,34,False


In [17]:
np.sum(simscore.column('Eagles Win'))/simscore.num_rows*100

47.260000000000005

In [18]:
simscore.column('Eagles')>simscore.column('Cowboys')

array([False, False,  True, ..., False, False, False], dtype=bool)

## Historic NFL scores
https://github.com/nflverse/nfldata/blob/master/data/games.csv

In [69]:
scores = Table.read_table('NFL_games.csv').where('season',are.above(2000))
scores

game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,home_score,location,result,total,overtime,old_game_id,gsis,nfl_detail_id,pfr,pff,espn,ftn,away_rest,home_rest,away_moneyline,home_moneyline,spread_line,away_spread_odds,home_spread_odds,total_line,under_odds,over_odds,div_game,roof,surface,temp,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
2001_01_CHI_BAL,2001,REG,1,2001-09-09,Sunday,13:00,CHI,6,BAL,17,Home,11,23,0,2001090902,17672,nan,200109090rav,nan,210909033,nan,7,7,nan,nan,10.5,nan,nan,33.5,nan,nan,0,outdoors,grass,83,10,00-0010560,00-0006300,Shane Matthews,Elvis Grbac,Dick Jauron,Brian Billick,Joseph Rider,BAL00,PSINet Stadium
2001_01_NO_BUF,2001,REG,1,2001-09-09,Sunday,13:00,NO,24,BUF,6,Home,-18,30,0,2001090906,17676,nan,200109090buf,nan,210909002,nan,7,7,nan,nan,-1.5,nan,nan,37.5,nan,nan,0,outdoors,astroturf,87,10,00-0001823,00-0008612,Aaron Brooks,Rob Johnson,Jim Haslett,Gregg Williams,Larry Mallam,BUF00,Ralph Wilson Stadium
2001_01_NE_CIN,2001,REG,1,2001-09-09,Sunday,13:00,NE,17,CIN,23,Home,6,40,0,2001090905,17675,nan,200109090cin,nan,210909004,nan,7,7,nan,nan,0,nan,nan,36,nan,nan,0,outdoors,grass,79,8,00-0001361,00-0009311,Drew Bledsoe,Jon Kitna,Bill Belichick,Dick LeBeau,John Smith,CIN00,Paul Brown Stadium
2001_01_SEA_CLE,2001,REG,1,2001-09-09,Sunday,13:00,SEA,9,CLE,6,Home,-3,15,0,2001090910,17680,nan,200109090cle,nan,210909005,nan,7,7,nan,nan,-4,nan,nan,38.5,nan,nan,0,outdoors,grass,81,12,00-0007091,00-0003535,Matt Hasselbeck,Tim Couch,Mike Holmgren,Butch Davis,Bill Etzler,CLE00,Cleveland Browns Stadium
2001_01_TB_DAL,2001,REG,1,2001-09-09,Sunday,13:00,TB,10,DAL,6,Home,-4,16,0,2001090911,17681,nan,200109090dal,nan,210909006,nan,7,7,nan,nan,-9,nan,nan,34,nan,nan,0,outdoors,astroturf,69,10,00-0008442,00-0020404,Brad Johnson,Quincy Carter,Tony Dungy,Dave Campo,Paul Labenne,DAL99,Texas Stadium
2001_01_DET_GB,2001,REG,1,2001-09-09,Sunday,13:00,DET,6,GB,28,Home,22,34,0,2001090903,17673,nan,200109090gnb,nan,210909009,nan,7,7,nan,nan,5.5,nan,nan,41.5,nan,nan,1,outdoors,grass,60,5,00-0000865,00-0005106,Charlie Batch,Brett Favre,Marty Mornhinweg,Mike Sherman,Aster Sizemore,GNB00,Lambeau Field
2001_01_PIT_JAX,2001,REG,1,2001-09-09,Sunday,13:00,PIT,3,JAX,21,Home,18,24,0,2001090908,17678,nan,200109090jax,nan,210909030,nan,7,7,nan,nan,3,nan,nan,37.5,nan,nan,1,outdoors,grass,83,10,00-0015700,00-0002110,Kordell Stewart,Mark Brunell,Bill Cowher,Tom Coughlin,Mack Gentry,JAX00,Alltel Stadium
2001_01_OAK_KC,2001,REG,1,2001-09-09,Sunday,13:00,OAK,27,KC,24,Home,-3,51,0,2001090907,17677,nan,200109090kan,nan,210909012,nan,7,7,nan,nan,-3,nan,nan,43,nan,nan,1,outdoors,grass,64,12,00-0005741,00-0006355,Rich Gannon,Trent Green,Jon Gruden,Dick Vermeil,Randall Beesley,KAN00,Arrowhead Stadium
2001_01_CAR_MIN,2001,REG,1,2001-09-09,Sunday,13:00,CAR,24,MIN,13,Home,-11,37,0,2001090901,17671,nan,200109090min,nan,210909016,nan,7,7,nan,nan,10,nan,nan,45,nan,nan,0,dome,astroturf,nan,nan,00-0020434,00-0003739,Chris Weinke,Daunte Culpepper,George Seifert,Dennis Green,Wayne McKreight,MIN00,Hubert H. Humphrey Metrodome
2001_01_IND_NYJ,2001,REG,1,2001-09-09,Sunday,13:00,IND,45,NYJ,24,Home,-21,69,0,2001090904,17674,nan,200109090nyj,nan,210909020,nan,7,7,nan,nan,-1.5,nan,nan,44.5,nan,nan,1,outdoors,grass,81,6,00-0010346,00-0016193,Peyton Manning,Vinny Testaverde,Jim Mora,Herm Edwards,Perry Havener,NYC00,Giants Stadium


In [58]:
es_array = scores.where('away_team','PHI').where('away_score',are.below(100)).column('away_score')
es_array

array([ 27.,  10.,  21.,  36.,  23.,  20.,   3.,  17.,  33.,  24.,  24.,
        37.,  25.,  19.,  38.,  27.,  27.,   7.,  23.,  21.,  14.,  23.,
        17.,  25.,  34.,  31.,  30.,  19.,  34.,   3.,  49.,  27.,  17.,
         7.,  10.,  37.,  10.,  21.,  10.,  17.,  17.,  21.,  24.,  38.,
        24.,  21.,  21.,  21.,  36.,  23.,  24.,  13.,   3.,  16.,  23.,
        33.,  28.,  10.,  38.,  37.,  20.,  40.,  26.,  13.,   7.,  20.,
         3.,  26.,  23.,  25.,  38.,   9.,  27.,  23.,  24.,  34.,  45.,
         0.,  14.,  35.,  28.,  27.,  19.,  59.,  26.,  30.,  38.,  31.,
        31.,  24.,  20.,  17.,  14.,  26.,  20.,  17.,   6.,  14.,  13.,
         6.,  33.,  23.,   7.,  33.,  20.,  36.,  31.,  49.,  27.,  30.,
        24.,  30.,  21.,  20.,  31.,  20.,  33.,  24.,  34.,  24.,  24.,
        20.,  16.,  33.,  14.,  35.,  35.,  29.,  23.,  20.,  23.,  23.,
        15.,  14.,  26.,  30.,  20.,  26.,  28.,  37.,  10.,  43.,  34.,
        41.,  21.,  23.,  34.,  24.,   7.,  23.,  3

In [59]:
es_array = np.append(es_array,scores.where('home_team','PHI').where('home_score',are.below(100)).column('away_score'))
es_array

array([ 27.,  10.,  21.,  36.,  23.,  20.,   3.,  17.,  33.,  24.,  24.,
        37.,  25.,  19.,  38.,  27.,  27.,   7.,  23.,  21.,  14.,  23.,
        17.,  25.,  34.,  31.,  30.,  19.,  34.,   3.,  49.,  27.,  17.,
         7.,  10.,  37.,  10.,  21.,  10.,  17.,  17.,  21.,  24.,  38.,
        24.,  21.,  21.,  21.,  36.,  23.,  24.,  13.,   3.,  16.,  23.,
        33.,  28.,  10.,  38.,  37.,  20.,  40.,  26.,  13.,   7.,  20.,
         3.,  26.,  23.,  25.,  38.,   9.,  27.,  23.,  24.,  34.,  45.,
         0.,  14.,  35.,  28.,  27.,  19.,  59.,  26.,  30.,  38.,  31.,
        31.,  24.,  20.,  17.,  14.,  26.,  20.,  17.,   6.,  14.,  13.,
         6.,  33.,  23.,   7.,  33.,  20.,  36.,  31.,  49.,  27.,  30.,
        24.,  30.,  21.,  20.,  31.,  20.,  33.,  24.,  34.,  24.,  24.,
        20.,  16.,  33.,  14.,  35.,  35.,  29.,  23.,  20.,  23.,  23.,
        15.,  14.,  26.,  30.,  20.,  26.,  28.,  37.,  10.,  43.,  34.,
        41.,  21.,  23.,  34.,  24.,   7.,  23.,  3

In [60]:
len(es_array)

440

In [61]:
cs_array = ...
cs_array

array([ 18.,  21.,  24.,  13.,  20.,   3.,  10.,  10.,  10.,  13.,  13.,
         6.,   7.,   3.,   7.,  14.,  35.,  17.,  38.,   0.,   0.,  10.,
        27.,   7.,  10.,  17.,  21.,  20.,   3.,  10.,  43.,   7.,  24.,
        28.,  34.,  13.,  10.,  21.,  10.,   7.,  24.,  17.,  45.,  24.,
        35.,  19.,  27.,  23.,  38.,  20.,  37.,  34.,  25.,  38.,  31.,
        28.,  20.,   6.,  28.,  27.,  24.,  14.,  14.,  14.,  13.,   6.,
        34.,  10.,  26.,  20.,   7.,  24.,  24.,  17.,   3.,   7.,  27.,
        21.,   7.,  33.,  38.,  26.,  14.,  24.,  27.,  16.,   7.,  27.,
        13.,  31.,  14.,  24.,   7.,  29.,  19.,  13.,  38.,  20.,  18.,
        16.,  21.,  17.,  30.,  17.,  24.,  28.,  24.,  26.,  34.,  30.,
        31.,  31.,  41.,  38.,  44.,  21.,  20.,  20.,  20.,   6.,  24.,
        19.,   7.,   6.,  27.,  24.,  30.,  35.,  35.,  17.,   7.,  13.,
        17.,  28.,  40.,  33.,   7.,  30.,  20.,   6.,   8.,  13.,  16.,
        17.,  27.,  22.,   0.,  36.,  22.,  31.,  1

In [62]:
cs_array = np.append(cs_array,scores.where('home_team','DAL').where('home_score',are.below(100)).column('away_score'))
cs_array

array([ 18.,  21.,  24.,  13.,  20.,   3.,  10.,  10.,  10.,  13.,  13.,
         6.,   7.,   3.,   7.,  14.,  35.,  17.,  38.,   0.,   0.,  10.,
        27.,   7.,  10.,  17.,  21.,  20.,   3.,  10.,  43.,   7.,  24.,
        28.,  34.,  13.,  10.,  21.,  10.,   7.,  24.,  17.,  45.,  24.,
        35.,  19.,  27.,  23.,  38.,  20.,  37.,  34.,  25.,  38.,  31.,
        28.,  20.,   6.,  28.,  27.,  24.,  14.,  14.,  14.,  13.,   6.,
        34.,  10.,  26.,  20.,   7.,  24.,  24.,  17.,   3.,   7.,  27.,
        21.,   7.,  33.,  38.,  26.,  14.,  24.,  27.,  16.,   7.,  27.,
        13.,  31.,  14.,  24.,   7.,  29.,  19.,  13.,  38.,  20.,  18.,
        16.,  21.,  17.,  30.,  17.,  24.,  28.,  24.,  26.,  34.,  30.,
        31.,  31.,  41.,  38.,  44.,  21.,  20.,  20.,  20.,   6.,  24.,
        19.,   7.,   6.,  27.,  24.,  30.,  35.,  35.,  17.,   7.,  13.,
        17.,  28.,  40.,  33.,   7.,  30.,  20.,   6.,   8.,  13.,  16.,
        17.,  27.,  22.,   0.,  36.,  22.,  31.,  1

In [63]:
len(cs_array)

420

In [64]:
simscore = Table().with_columns('Eagles', np.random.choice(es_array,5000),
                                'Cowboys', np.random.choice(cs_array,5000))
simscore

Eagles,Cowboys
34,30
34,21
16,27
33,14
27,33
24,17
20,13
21,22
7,13
29,31


In [65]:
simscore=simscore.with_columns('Eagles Win', simscore.column('Eagles')>simscore.column('Cowboys'),'Tie',simscore.column('Eagles')==simscore.column('Cowboys'))
simscore

Eagles,Cowboys,Eagles Win,Tie
34,30,True,False
34,21,True,False
16,27,False,False
33,14,True,False
27,33,False,False
24,17,True,False
20,13,True,False
21,22,False,False
7,13,False,False
29,31,False,False


In [66]:
simscore=simscore.where('Tie',False)
simscore

Eagles,Cowboys,Eagles Win,Tie
34,30,True,False
34,21,True,False
16,27,False,False
33,14,True,False
27,33,False,False
24,17,True,False
20,13,True,False
21,22,False,False
7,13,False,False
29,31,False,False


In [67]:
np.sum(simscore.column('Eagles Win'))/simscore.num_rows*100

50.616252350114898